### ISSUE TITLE
Can't load elements from non-root folder

### ISSUE THREAD

**Issue by ErwinJobse** [typingbeaver/snake-label#10]
When you try to load the project from a link like: domain.tld/folder, some links won't work. 

It is because some links look like this:` <link rel="apple-touch-icon" sizes="180x180" href="/icons/apple-touch-icon.png" />
`
The "/" at the beginning refers to the root of the server, where it isn't at the moment. Removing it will use the current folder as the root.

**Comment by typingbeaver** [comment]
Fixed. :)
