### ISSUE TITLE
Add description on which output format (Ausgabeformat) you have to choose for stamps

### ISSUE THREAD

**Issue by TomTomNavigator** [typingbeaver/snake-label#14]
I am always struggling on which output format I have to choose on the Deutsche Post webshop - maybe you can clarify and simply add it to the readme? :-)

<img width="1060" alt="image" src="https://github.com/typingbeaver/snake-label/assets/6422799/e7c3e2a5-e092-4c06-8b35-0d62a7e51582">

**Comment by seneca13** [comment]
As You can see, there are only 2 different sizes (62x100 & 70x100) you can choose at Deutsche Post (label with address).
You could have just used the [Druckvorschau als PDF] (= print preview, PDF) and convert the result (PDF) with snake-label to see the results...
But to make it short: 
It doesn't really matter witch export format You choose, the result ist (almost) the same.

**Comment by TomTomNavigator** [comment]
I think I am blind - never seen the Druckvorschau ...  anyhow, no hard feelings, thx for Snake Label and the quick reply!
