### ISSUE TITLE
New label type for Dutch DHL

### ISSUE THREAD

**Issue by ErwinJobse** [typingbeaver/snake-label#8]
Hi,

Would you be interested to add a Dutch DHL label? 

I added an example PDF. 
[removed document]

Kind regards,

**Comment by typingbeaver** [comment]
Hi,
thanks for the issue!

Yes, I can add it in the next days!
As the label contained a real address, I have removed it from the issue for the sake of data protection.

Stay tuned! :)

**Comment by typingbeaver** [comment]
Aaaand done. And that even before tomorrow.
Hope you like it!

(Original label is now deleted too on my site as I have a sample now.)

**Comment by ErwinJobse** [comment]
Thank you. 

There is only a small problem when you send the package to a pickup location. Then the address is 1 line longer, causing the tracking code to go away. 
[removed document]

**Comment by typingbeaver** [comment]
Welp, that is very unfortunate as the label seems to have no fixed structure, so shifting like this can occur...
I will take a look into that again. Maybe I will come up with a solution.

**Comment by ErwinJobse** [comment]
I can't find an example of the address being smaller or bigger than the two that I provided you with. So adding a new type for a DHL ServicePoint might be the solution.

**Comment by typingbeaver** [comment]
I hope they work fine now. We have to live with all these variations until I rework my object structure. :D

The first label (4/4) was shifted to the right a little, whereas the other labels aren't. I did correct the crop area for that one too, hope it still works for new labels. :)

**Comment by ErwinJobse** [comment]
This works perfectly :) 

However, there is no need for the 5_4 and 5_5 labels, since the "From" is always 4 lines, but the "To" can be 4 or 5 lines.

**Comment by typingbeaver** [comment]
`5_4` and `5_5` exist just in case anybody might use the company field as sender. The other ones would be partially broken again then...
